### ISSUE TITLE
Checking file-naming convention

### ISSUE THREAD

**Issue by kwojcik-blockether** [codeclimate/codeclimate-grep#8]
I'm having an issue understanding whereas `codeclimate-grep` is capable of checking file naming conventions. What I want to achieve is to check whether a file name `foo_bar.js` is written in `kebab-case`.
AFAIK `codeclimate-grep` is only searching for patterns inside a file and is unable to check the file name am I right?

**Comment by pointlessone** [comment]
Hi Karol,

Unfortunately, this engine is designed to only check files content.

Nonetheless, I think it's possible to "hack" it to do what you want but it's not a supported use case.

Try this config:

```yaml
patterns:
  kebab:
    pattern: .*
    annotation: "Don't use _ in file names"
    severity: minor
    categories: Bug Risk
    path_patterns:
      - "**/*_*"
```
